### ISSUE TITLE
Assemblytics

### ISSUE THREAD

**Issue by anorris8** [malonge/RagTag#10]
I loved the integration of Assemblytics SV caller with RaGOO. Are there plans to integrate Assemblytics into RagTag? Or maybe I missed that flag/output.

**Comment by malonge** [comment]
Hi there,

Thanks for reaching out. Currently, there is no plan to integrate SV calling. This is primarily a design choice to make the software a little more simple and therefore easier to test and debug.

However, I appreciate the feedback and will think about it a little bit. There is always the option to integrate it in the future. It is good to hear from users because I wasn't really sure how many people were utilizing that functionality. 

Thanks,
Mike
