### ISSUE TITLE
scaffolding with inverted genomic region

### ISSUE THREAD

**Issue by Lin-Yuying** [malonge/RagTag#105]
Hi, 

I recently used RagTag for chromosome-level assemblty with 10x linked read data. We are pretty clear that there should be a ~20Mb inversion when compared to the reference genome. However, after visualization using last, I didn't find any inversions. But I did find breaking points at the boundary of inversion in last dotplot.

The reference genome and query genome are ~1Gb. Command that I used is `python ragtag.py scaffold /path/reference.fa query_10x.fa`.

I am thinking maybe I miss any important parameters or I mistakenly used the wrong command for my analysis. Can you help with this? 

Thanks in advance!

Best,
Lin

**Comment by malonge** [comment]
Hi there,

When you say that you saw "breaking points", does that mean that you found gaps at the inversion boundaries? If so, then yes the inversion will be incorrectly flipped to match the reference genome. In order to be properly oriented, the inversion will need to be within a contig that includes sufficient flanking sequence. So it's not a matter of parameters but rather just that the contiguity is not sufficient to properly orient this inversion.
