### ISSUE TITLE
Error when correcting with reads

### ISSUE THREAD

**Issue by anorris8** [malonge/RagTag#11]
Hi Michael,

Thanks for the improved version of RaGOO! 

RagTag is running great except when I include corrected reads fastq. Unfortunately, the log makes it seem like the `ragtag.py correct` completed successfully even though it does not produce the `ragtag_output/contigs.corrected.fasta` file. I've tried it w/ and w/o `-u`, in case that helps.

***

`ragtag.py correct -t 16 -u --aligner minimap2/minimap2 -R corr_reads.fastq -T corr reference.fasta contigs.fasta`

***

`Mon Jul 20 22:43:51 2020 --- RagTag v1.0.0`   
`Mon Jul 20 22:43:51 2020 --- CMD: /work/virtualenvs/venv_devopspy/bin/ragtag_correct.py -t 16 -u --aligner minimap2/minimap2 -R corr_reads.fastq -T corr reference.fasta contigs.fasta`  
`Mon Jul 20 22:43:51 2020 --- Mapping the query genome to the reference genome`  
`Mon Jul 20 22:43:51 2020 --- Running: minimap2/minimap2 -x asm5 -t 16 reference.fasta contigs.fasta > ragtag_output/c_query_against_ref.paf 2> ragtag_output/c_query_against_ref.paf.log`  
`Mon Jul 20 22:48:39 2020 --- Finished running : minimap2 -x asm5 -t 16 reference.fasta contigs.fasta > ragtag_output/c_query_against_ref.paf 2> ragtag_output/c_query_against_ref.paf.log`  
`Mon Jul 20 22:48:39 2020 --- Reading whole genome alignments`  
`Mon Jul 20 22:48:47 2020 --- Filtering and merging alignments`  
`Mon Jul 20 22:48:52 2020 --- Validating putative query breakpoints via read alignment.`  
`Mon Jul 20 22:48:52 2020 --- Aligning reads to query sequences.`    
`Mon Jul 20 22:48:52 2020 --- Running: minimap2/minimap2 -ax asm5 -t 16 contigs.fasta corr_reads.fastq > ragtag_output/c_reads_against_query.sam 2> ragtag_output/c_reads_against_query.sam.log`    
`Mon Jul 20 22:52:28 2020 --- Finished running : minimap2/minimap2 -ax asm5 -t 16 contigs.fasta corr_reads.fastq > ragtag_output/c_reads_against_query.sam 2> ragtag_output/c_reads_against_query.sam.log`  
`Mon Jul 20 22:52:28 2020 --- Compressing, sorting, and indexing read alignments`

***
ragtag_output:
`c_query_against_ref.paf`  
`c_query_against_ref.paf.log`  
`c_reads_against_query.bam`  
`c_reads_against_query.sam`  
`c_reads_against_query.sam.log`

**Comment by malonge** [comment]
Hi there,

Thanks for bringing this to my attention. It's not clear from the log, but the log is actually truncated. In future versions, I will add a log message that signals the end of the program. Something like "bye".

So something went wrong between compressing and sorting the read alignments. Is the sam/bam file empty? Aside from that bam file, we should also see a sorted bam file named `c_reads_against_query.s.bam`

It is strange that things failed yet there is no error message from pysam or anything else. Would you be willing to share the data so that I can reproduce the error? Unfortunately, it looks like the error is silent which makes it hard to debug. 

You may be eager to get results in the meantime. Assuming the `c_reads_against_query.sam` looks ok, you can compress, sort and index it yourself with samtools (`view`, `sort` and `index`). Just be sure to name the sorted bam file `c_reads_against_query.s.bam` and put it in the same `ragtag_output` directory. Then, when you run ragtag with the same command, it will recognize the sorted bam file and it will (hopefully) proceed as normal.

Thanks,
Mike

**Comment by malonge** [comment]
I should be more clear - aside from just checking if the SAM/BAM file is empty, please check the general integrity of the files with samtools. I have a feeling something is going wrong with pysam here.

**Comment by anorris8** [comment]
Sorry - I just realized the output got cutoff in my original post. I do have the following files. I'll check them out now.
`c_reads_against_query.s.bam` 
`c_reads_against_query.s.bam.bai`

**Comment by anorris8** [comment]
It turned out to be an issue with my reads file. Thanks!
