### ISSUE TITLE
Scaffold inserting strings of 100 N's?

### ISSUE THREAD

**Issue by cizydorczyk** [malonge/RagTag#157]
I understand scaffold has the -r, -g, and -m paramters to infer gap sizes, set the min and max inferred gap sizes.

When I run ragtag scaffold with these set to something like -r -g 2 -m 1000000 (to essentially not limit these in my current assembly), I end up with strings of 100 N's inserted in various places, in addition to appropriately sized gaps. 

Several instances of 100 N's inserted is not coincidence; where are these coming from if not from these parameters? Does ragtag scaffold default to 100 N's in some other context?

Thanks

**Comment by malonge** [comment]
Hi there,

Thanks for the question. You can find details in the paper. Indeed, there are certain conditions where RagTag defaults to 100 bp.

**Comment by cizydorczyk** [comment]
Right -- but which condition might be triggering in this case? I am explicitly trying to avoid any defaulting and am setting options to avoid it, but it still happens.

Am I missing something?

**Comment by nickgladman** [comment]
@cizydorczyk : the RagTag paper discusses this in the RagTag "scaffold" section:

"All inferred gap sizes must be at least 1 bp, and if the inferred gap size is too small (-g or less than 1) or too large (-m), it is replaced with an “unknown” gap size of 100 bp."

**Comment by malonge** [comment]
Hi there,

Thanks for your question. At least one condition is when the evidence suggests that sequences overlap, thus suggesting a negative gap length. That is what is meant by "All inferred gap sizes must be at least 1 bp". 

There is no way to guarantee that no 100bp gaps will be used. Sometimes, the evidence necessitates 100bp gaps even if setting -r, -g, and -m.

**Comment by kfpbennett** [comment]
Hello. I am encountering unusual behavior re: gap sizes. I am inferring gap sizes (-r) and using -g 20. The log file states the following:

Mon Apr  6 16:54:03 2026 --- INFO: 27 inferred gap
Mon Apr  6 16:54:03 2026 --- INFO: 140 adjacent contig within min distance (20) of each other
Mon Apr  6 16:54:03 2026 --- INFO: 26 inferred gaps exceed length threshold (100000)

But in the AGP file, there are 27 non-100-bp gaps and 166 gaps of 100-bp. It seems it is setting all non-inferred gaps to 100 rather than 20 or 100000. This may be related to the previous question?

**Comment by kfpbennett** [comment]
OK I fixed this by changing the scaffold.py script as follows:

if i_gap_size <= min_gap_size:
    pad_sizes[i].append(100) # changed to append(min_gap_size)
    gap_types[i].append("U") # changed to append("N") 
    g_small += 1
elif i_gap_size > max_gap_size:
    pad_sizes[i].append(100) # changed to append(max_gap_size)
    gap_types[i].append("U") # changed to append("N")
    g_large += 1
