### ISSUE TITLE
Adjust default gap size

### ISSUE THREAD

**Issue by mrvollger** [malonge/RagTag#186]
Hi @malonge,

Is there any way to adjust the default gap size of 100bp in scaffold? E.g. make all the inserted gaps 10,000bp. 

Thanks,
Mitchell

**Comment by malonge** [comment]
Unfortunately this is not supported. If gap sizes are not inferred, then they are set to 100 bp because this is the AGP standard for gaps of unknown size. The other option is to try to infer gap sizes with -r. 

I recommend writing a script to parse the output agp file for a custom non standard gap size. Sorry for the inconvenience.
