### ISSUE TITLE
Using a two contig reference as the main ref.fa and unicycler output as the query

### ISSUE THREAD

**Issue by gracem97** [malonge/RagTag#24]
Hi Mike,

I am running correction on a flye assembly that has 2 contigs with a unicycler that has 125. This gives a corrected.fasta with 12 contigs. When I scaffold it I get this:

>1_RagTag
>11_RagTag
>2_RagTag
>3_RagTag
>39_RagTag
>4_RagTag
>5_RagTag
>6_RagTag
>7_RagTag
>84_RagTag

Do you think it's better to use a single refseq instead of an segmented one? 
My genome is ~ 6,800,000bp

Thank you,
Grace

**Comment by malonge** [comment]
Hi Grace,

Can you share the commands you used to run ragtag? It would be strange to go from 125 to 12 contigs during correction. Correction should yield no fewer contigs than the input, since correction is just the breaking of input contigs. If the flye assembly was used as the query and the unicycle assembly used as the reference, that would be more sense. If that is the case, I can give you some suggestions. 

Thanks,
Mike

**Comment by gracem97** [comment]
HI Mike,

I used placed minimap2 in my path then python3 ragtag.py correct flye.fasta unicyc.fasta and python3 ragtag.py scaffold flye.fasta ragtag_output/unicyc.assembly.corrected.fasta.

**Comment by malonge** [comment]
Hi Grace,

Thanks for sharing your data. The unicycler assembly you provided actually only had 75 contigs, and `Bif1.unicyc.corrected.fasta` had 76 contigs, indicating that a single contig ("3") was broken one time during correction.

It appears that scaffolding also generated 76 contigs and that is beacuse two of the 76 corrrespond exactly to the two flye contigs. 

Unicycler contig "1" corresponds to flye "contig_1" and Unicycler contig "2" corresponds to flye "contig_2". In fact, they have exactly the same length. Are they the exact same sequences?

I am not sure why we are getting different results. Can you confirm that your query assembly has 75 contigs rather than 125?

Thanks

**Comment by gracem97** [comment]
Ok, I switched the flye and unicyc... my bad. 

Now, I see that there are 75 contigs in my unicyc.fasta. 
I still have the idea that the assembly did not work because the output said there are 2 ragtag and a bunch of other numbers. But the stats say there are 0 misplaced sequences. Thanks for your help.

>contig_1_RagTag
>contig_2_RagTag
>10
>11
>12
>13
>14
>15
>16
>17
>18
>19
>20
>21
>22

**Comment by malonge** [comment]
Hi there,

Here is what my stats file looks like:

```
placed_sequences  placed_bp  unplaced_sequences  unplaced_bp  gap_bp  gap_sequences
2                 5652627    74                  286548       0       0
```

So this says that `286548/(286548+5652627) = 4.8%` of sequence is unplaced, which is usually pretty good. If you are curious about why those other contigs were not placed, you can look at the intermediate `query_against_ref.paf` file to see what the alignments for the unplaced contigs look like.

I will close this for now but feel free to reopen if anything comes up.

Thanks
