### ISSUE TITLE
Bam file for "correct" module

### ISSUE THREAD

**Issue by harmeet1990** [malonge/RagTag#56]
Hi

Can I somehow directly give the minimap2 aligned bam file (instead of the fasta read file) in the validation options?

**Comment by malonge** [comment]
Hi there,

RagTag won't overwrite such a file if it already present, so long as you avoid the `-w` parameter. So if you copy the file to the output directory and rename it, that should work:

```
mkdir ragtag_output
cd ragtag_output
ln -s /path/to/sorted/file.s.bam c_reads_against_query.s.bam
ragtag.py correct ref.fa query.fa -R reads.fasta -T $TECH
```

You still have to provide the reads in the command line argument so that RagTag knows what to do. However, it won't remake the BAM file.

P.S. the BAM file name will change in v2.0 which will be released soon.
