### ISSUE TITLE
How does the RagTag fill the gaps & distinguish the misassemblies & SVs?

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [malonge/RagTag#6]
Hey there!
I have a couple of questions on the RagTag. For example,  we have two chromosome-length genome assemblies of Apis mellifera (Fig.) Amel_HAv3.1(ref) and Amel_INRA_1(query). I want to fill the gap in the Chr 2 (blue circle), and solve the misassemblies in Chr 6 (red circle). I run the following command: ragtag.py correct ref.fasta query.fasta
Questions :
1) Whether the RagTag will fill the gap in the query using the corresponding fragment from the ref OR using the unplaced contigs of the query OR it will be a consensus? 
2) How does the RagTag distinguish the misassemblies and real structural variants? I want to solve the misassemblies and keep SVs.
Thanks!
Ural Yunusbaev

![image](https://user-images.githubusercontent.com/31982042/86252711-82d79b00-bbee-11ea-9a54-69798b27efdf.png)

**Comment by malonge** [comment]
Hi Ural,

>Whether the RagTag will fill the gap in the query using the corresponding fragment from the ref OR using the unplaced contigs of the query OR it will be a consensus?

While RagTag can estimate gap sizes, it does not fill gaps with reference sequence. This is because RagTag scaffolding strictly orders and orients input query sequences without adding or subtracting any sequence.  This has some nice advantages and gives good guarantees, but the downside is that it doesn't fill gaps with reference sequences. If it were me personally, since it is only one gap, I would do it manually. Someone in my lab is working on a tool to automate this, though it is not quite ready. Also, maybe [Ragout](https://github.com/fenderglass/Ragout) has this functionality.

>How does the RagTag distinguish the misassemblies and real structural variants? I want to solve the misassemblies and keep SVs.

There is only one validation that RagTag can use to verify misassemblies and that is by aliging reads and querying the coverage near a putative misassembly. This is triggered using `-R` and `-T` with `ragtag.py correct`. Though this helps to reduce false positives, it is still fairly senstive and may still break at true SVs. You can limit the sensitivity by adjusting `-v` `--max-cov`, and `--min-cov`. However, if one wants to be _extra_ careful to not break at true SVs, I recommend just not using the correction module.

Let me know if you have further questions.
Thanks

**Comment by Ural-Yunusbaev** [comment]
Thank you!
