### ISSUE TITLE
pair-end and ONT reads

### ISSUE THREAD

**Issue by mictadlo** [malonge/RagTag#62]
Hi,
Does RagTag support pair-end reads in FASTQ format and is it possible to combine them with ONT (7x coverage)?

How would the command for the above data look like?

Thank you in advance.

Micha

**Comment by malonge** [comment]
Hi Micha,

Is this in reference to ragtag correct? For the validation feature?

**Comment by mictadlo** [comment]
Yes, it is correct. I do not understand how to use `-F`, `-R`, and `-T`.

**Comment by malonge** [comment]
I do not recommend mixing data types since the aligner should use parameters specific to each technology. Also, RagTag does not make use of paired-end information, so you can provide both read pairs, but they will just be treated as single-end.

Your ONT is probably too low coverage, so I suggest you use the paired-end reads instead. You can make a file `reads.fofn` with the files names:

```
reads1.fastq
reads2.fastq
```

And then run with the following command

`ragtag.py correct -F reads.fofn -T sr ...`

I'll close the issue for now, but let me know if you have any additional questions.

Thanks!

**Comment by mictadlo** [comment]
Thank you.
