### ISSUE TITLE
Polyploid Scaffold

### ISSUE THREAD

**Issue by WangYuan20190517** [malonge/RagTag#63]
Hi ,
I want to scaffold an allotetraploid of 52 chromosomes to a diploid of 26 chromosomes.  Whether RagTag can complete this work, and what parameters do I need to adjust?

Thanks
wy

**Comment by malonge** [comment]
Hi there,

You will need to separate the subgenomes before using ragtag, otherwise, you may end up with homeologous contigs laid out adjacent to each other along the chromosomes, causing false duplication signal. Once you have the subgenomes separated, you can run ragtag for each subgenome individually.

Thanks,
Mike
