### ISSUE TITLE
Misassemblies vs. True Variation

### ISSUE THREAD

**Issue by mictadlo** [malonge/RagTag#73]
Hi,
I am confused between the Introduction and Misassemblies vs. True Variation of the `correct` step. Firstly, *Query sequences are only broken at points of putative disassembly* but later on *Reference-guided misassembly signatures are sometimes caused by true biological structural variation if the reference and query assemblies represent distinct genotypes (or haplotypes). *

> Introduction
> RagTag offers a correction module that uses a reference genome to identify and correct potential misassemblies in a query assembly. RagTag also provides the option to verify putative misassemblies by aligning reads (from the same genotype) to the query assembly and observing read coverage near misassembly break points. In all cases, sequence is never added or subtracted. Query sequences are only broken at points of putative disassembly.

> Misassemblies vs. True Variation
> Reference-guided misassembly signatures are sometimes caused by true biological structural variation if the reference and query assemblies represent distinct genotypes (or haplotypes). The read validation feature should help to avoid some of these misassembly false positives, and the validation sensitivity can be tuned with command line parameters. However, it is ultimately up to the discretion of the user to decide if misassembly correction is appropriate. One should validate all RagTag results with independent data (usually physical, optical, or genetic maps), when possible.

After we assembled our reference sequence, we have applied BioNano. Next, BioNano's SuperScaffolds were used with Hi-C with help of 3d-DNA and Juicer. Finally, we loaded the results into JuiceBox and did some manual corrections.

In order to validate RagTags output, do I have to rerun 3d-DNA and Juicer on our final reference assembly or do I map the Hi-C data manually (if yes then what tools and settings are recommended)?

Thank you in advance,

Michal

**Comment by malonge** [comment]
Hi Michal,

If you have independent maps, you can use them to validate any stage of the assembly process. Let's suppose RagTag recommends breaking `ctg1`. Then you can align your Hi-C to the assembly and look at the contact heatmap across `ctg1` to see if the Hi-C also supports the break.

Later on, after your assembly has been completely scaffolded, you can (and should) re-align the Hi-C and check the overall structural accuracy. And this all goes for Bionano as well. However, one must consider the consequences of a false positive RagTag correction break. One might break `ctg1` when it shouldn't have been broken, and then later, the Bionano/Hi-C might put `ctg1` back together, though with a gap joining the two subcontigs. Or maybe the Bionano/Hi-C are not able to put `ctg1` back together because the subcontigs are too small.

Anyways, I hope this answers your question. In short, one should use independent maps to validate every stage of the assembly. Assembly improvement is often deciding whether or not to break contigs or whether or not to join distinct contigs. Independent maps can help you make those decisions.

Thanks,
Mike

p.s. these days, assemblies are much more accurate than they used to be, so correction is probably not needed (or may even be detrimental) for assemblies with good data.

**Comment by malonge** [comment]
To be clear, this validation is usually manual, and RagTag does not necessarily provide an automated way to do this. The only exception is RagTag [merge](https://github.com/malonge/RagTag/wiki/merge) which can be useful for validating joins.

**Comment by dtusso2020** [comment]
Hello Michael

In past days I sent to your e-mail two plots of some alignments made comparing ragtag correct and ragtag scaffold without correct. I found differences between both alignments, where the file generated from correct perfectly matched with the reference, but the alignment generated by scaffold without correct had two inversions and two gaps. My question is how do I determine that the corrections made are misassemblies and are not true variations. If I don't have Hi-C alignments, how could I do this validation manually and decide whether to use the corrected file or not? I am confused about this. 
Thank you

**Comment by malonge** [comment]
Hi there,

This is a fairly advanced and in-depth topic and I unfortunately do not quite have the time to provide all the details here. However, there are some good papers that go over this.

To start, you can check out [this paper](https://www.nature.com/articles/s41586-021-03451-0) from the VGP. 

You may also find our human T2T [polishing paper](https://www.biorxiv.org/content/10.1101/2021.07.02.450803v1.abstract) to be useful.

Anyways its a difficult yet fun subject. Good luck!
