### ISSUE TITLE
Gaps sequences?

### ISSUE THREAD

**Issue by jantonid** [malonge/RagTag#9]
Hello Mike:
I am comparing the statistics from the use of ragtag on a draft assembly to several possible reference assemblies.  (Actually the draft assembly is a bit different for each reference, because the "correct" script is used before each reference "scaffold" script.)  What I am wondering is what the "gap_bp" and "gap_sequences" actually mean?  I used the default of 100 for gap lengths, rather than inferring them.  Are the gap sequences and length also part of the unplaced sequences and length, or some third category of sequences?  Below are my results from running ragtag with six different references.  (It is looking like the first one is "best" based on overall placed length, but it also has the largest gap length...)

placed_sequences | placed_bp | unplaced_sequences | unplaced_bp | gap_bp | gap_sequences
-- | -- | -- | -- | -- | --
4,764 | 601,032,099 | 728,635 | 511,410,804 | 474,800 | 4,748
4,160 | 584,072,430 | 729,360 | 528,370,473 | 413,200 | 4,132
651 | 447,227,915 | 732,721 | 665,214,988 | 62,800 | 628
2,047 | 489,225,429 | 731,480 | 623,217,474 | 196,300 | 1,963
2,091 | 535,970,451 | 731,502 | 576,472,452 | 207,800 | 2,078
917 | 467,971,426 | 732,416 | 644,471,477 | 90,300 | 903

Thanks for your help and insight!
Jenny

**Comment by malonge** [comment]
Hi Jenny,

Thanks for your question. As I build my docs, I will be sure to add a description of the stats file. First of all, could you share an example command that you used? 

Since you used the default gap size, the total amount of gaps will just be the number of adjacent contig pairs * 100, since each adjacent contig pair has a 100 bp gap in between. If you used the `-C` option, RagTag will build a chr0 which will use gaps for padding, thus increasing the total number of gaps, even though those gaps are only between unplaced sequences.

Without `-C`, more gaps probably just means that more contigs were placed, and therefore there were more adjacent contig pairs and gaps between them. With `-C`, the variation in the number of gaps probably results from variation in the correction phase and therefore the total number of contigs input into the scaffolder. 

Let me know if anything needs clarification. 

Thanks,
Mike

**Comment by jantonid** [comment]
Hello Mike,

Thanks for your reply.  What I am trying to do is get a pseudochromosome assembly of my species of interest (with a desired 14 chromosomes/linkage groups + unplaced scaffolds).  This way I have a reference assembly of my species of interest for downstream applications.  Does that make sense, and do the parameters make sense?  In all my cases, I start with a scaffold-level assembly (733,333 scaffolds) of my species of interest as my query (which is then corrected), and I use that with the scaffold command with a chromosome-level reference assembly of a different but related species.

Here are the commands for the first case on the list above (a reference with n=16 chromosomes):

ragtag.py correct -u -f 500 -t 30 \
--mm2-params '-x asm20' \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_012066045.1_ASM1206604v1_genomic.fna \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_010015005.1_ASM1001500v1_genomic.fa \
&> ragtag.correct.mm2.500.mulberry.logfile

ragtag.py scaffold -u -f 500 -q 0 -t 30 \
--mm2-params '-x asm20' \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_012066045.1_ASM1206604v1_genomic.fna \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/ragtag_new/ragtag_output/GCA_010015005.1_ASM1001500v1_genomic.corrected.fasta \
&> ragtag.scaffold.mm2.500.mulberry.logfile

Thank you!
Jenny

**Comment by malonge** [comment]
Hi Jenny,

I think I remember you from a previous conversation. Yes, I think those commands look great. It appears that you did not use `-C` which confirms that the additional gaps are the result of more localized contigs. So the more contigs that are localized, the more gaps there will be between adjacent contigs. And the individual correction runs could also affect the localization stats as well.

Thanks,
Mike

**Comment by jantonid** [comment]
Thanks Mike,
Quick question--are you using the term contig interchangeably with how I am using the term scaffold?
--Jenny

**Comment by malonge** [comment]
Hi Jenny,

Yes, you are right. I should just say "query sequences", which in your case are scaffolds.

Thanks,
Mike
