### ISSUE TITLE
How to understand patch

### ISSUE THREAD

**Issue by Yutang-ETH** [malonge/RagTag#96]
Hi @malonge 

I checked issues #75 but I am still a little bit confused about patch. 
Let's say I have a fragmented assembly with contigs, and a chromosome-scale reference, can I use patch to scaffold the contig-level assembly based on the chromosome-scale reference? It also looks like patch could do scaffolding and gap-filling in one shot, do I understand it correctly?

Or, should I do ragtag scaffold first to connect contigs to scaffolds and then use patch to fill gaps in the new scaffolds? Could you please explain to me? Thank you very much.

Best wishes,
Yutang

**Comment by malonge** [comment]
Hi there,

Either approach is valid. `scaffold` is more sensitive and it will usually make more joins since gap-filling information is not required. Since gap-filling info is required for `patch`, it can be less sensitive. For this reason, it can be wise to run `scaffold` first. That way, all possible joins are made. Then, you can fill gaps with `patch`. Even if a gap wasn't filled, at least it was already joined by `scaffold`.

Of course, each situation is different. More details can be found on the [Wiki](https://github.com/malonge/RagTag/wiki).

**Comment by Yutang-ETH** [comment]
Thank you very much for your explanation. Yes, I did scaffolding first and now I am running patching, however I noticed that patch breaks scaffolds into small sequences and then align my reference chromosomes to these small sequences. I used Nucmer for alignment and it's super slow, it has been running all most 3 days now. Did I do something wrong?

Best wishes,
Yutang

**Comment by malonge** [comment]
Not necessarily. Nucmer can be quite slow on larger genomes.

**Comment by Yutang-ETH** [comment]
OK, I see. Thank you very much for your confirmation. If I get good results, I will let you know.

Best wishes,
Yutang
