### ISSUE TITLE
Why is the number of chromosomes not fixed when the *.agp files of multiple reference  are merged  

### ISSUE THREAD

**Issue by lxxiaoxiaLi** [malonge/RagTag#97]
Hi @malonge
when I run command and find each reference' ragtag.scaffold.fasta has 12 chromosomes, 

# scaffold with multiple references/maps
ragtag.py scaffold -o out_1 ref1.fasta query.fasta
ragtag.py scaffold -o out_2 ref2.fasta query.fasta

But after run this command：ragtag.py merge query.fasta out_*/*.agp other.map.agp, the final file ragtag.merge.fasta has not 12 chromosomes, why？Could you please explain to me? 
If I want to get 12 chromosomes, How should I set the parameters? Thank you very much.

**Comment by malonge** [comment]
Hi there,

scaffolds can break if there is disagreement about how to order and orient the contigs according to the alignments to the respective references. These ambiguities could lead to breaks in scaffolds.

This is often caused by spurious scaffolding of smaller contigs. To test this, you can try increasing `-l`.

Also, sometimes scaffolding with Nucmer rather than Minimap2 can help.

If you'd like to get back to 12, you can pick one of the references and run ragtag `scaffold`.
